try:
    print(x)
except:
    print("An exception occurred")
finally:
    print("This code will run no matter what")